In [75]:
import numpy as np
import pandas as pd
from google.colab import drive

In [76]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [77]:
hackathons = pd.read_csv('/content/drive/MyDrive/Datasets/all_hackathons.csv')

In [78]:
hackathons = hackathons.drop('Count', axis=1)

In [79]:
hackathons.head()

,id,Hackathon Slug,Title,Status,URL,Submission Period,Themes,Prize Amount,Registrations Count,Organization,Winners Announced,Projects Gallery
0,17851,bpt-hackathon,University of Bridgeport Hackathon,ended,https://bpt-hackathon.devpost.com/,"Apr 14 - 16, 2023","['E-commerce/Retail', 'Enterprise', 'Web']",2700,23,University of Bridgeport,True,https://bpt-hackathon.devpost.com/project-gallery
1,17217,hackenosia,HACKENOSIA,ended,https://hackenosia.devpost.com/,"Mar 25 - 26, 2023","['Beginner Friendly', 'Web', 'Mobile']",45000,23,"DeVerse Club, VGI",False,https://hackenosia.devpost.com/project-gallery
2,17853,hacktrix1,Hacktrix_1.0,ended,https://hacktrix1.devpost.com/,"Mar 17 - 23, 2023","['Blockchain', 'Health', 'Productivity']",1211,23,Sri Krishna College of Technology,False,https://hacktrix1.devpost.com/project-gallery
3,16823,orange-inter-odc-makeathon,Orange Inter-ODC Makeathon 2022,ended,https://orange-inter-odc-makeathon.devpost.com/,"Dec 03 - 04, 2022","['IoT', 'Enterprise', 'Web']",6000,23,Orange Digital Center,True,https://orange-inter-odc-makeathon.devpost.com...
4,16833,mais-bootcamp-fall-2021,MAIS Bootcamp Fall 2022,ended,https://mais-bootcamp-fall-2021.devpost.com/,"Nov 23 - Dec 01, 2022",['Machine Learning/AI'],0,23,McGill AI Society,False,https://mais-bootcamp-fall-2021.devpost.com/pr...

In [80]:
hackathons.shape[0]

11418

In [81]:
projects = pd.read_csv('/content/drive/MyDrive/Datasets/hackathon_projects.csv')

In [82]:
projects.head()

,Hackathon ID,Hackathon Slug,Project Title,Project Description,Project Link,Participants Count,Likes,Comments
0,17851,bpt-hackathon,Lyceum,Unlock Limitless Learning with AI 🤖,https://devpost.com/software/lyceum,4,4,0
1,17851,bpt-hackathon,PostAI,Help elevate your company's social media prese...,https://devpost.com/software/postai,4,0,0
2,17851,bpt-hackathon,LiquidLife,LiquidLife is a social enterprise project dedi...,https://devpost.com/software/liquidlife,2,3,0
3,17851,bpt-hackathon,CRYPTOGRAPHIC FARMING,Reforming conventional Agri perspective,https://devpost.com/software/cryptographic-far...,3,3,2
4,16823,orange-inter-odc-makeathon,oliot,un projet qui vise a minimiser les pertes d'ea...,https://devpost.com/software/oliot,1,0,0

In [83]:
projects.shape[0]

345804

### Filter by Status

In [84]:
filtered_hacks = hackathons[
    hackathons["Status"].str.lower() == "ended"
]

In [85]:
filtered_hacks.shape[0]

11262

### Filtering by Winners Announced

In [86]:
filtered_hacks['Winners Announced'].unique()

array([ True, False])

In [87]:
filtered_hacks = filtered_hacks[
    filtered_hacks["Winners Announced"] == True
]

In [88]:
filtered_hacks.shape[0]

7172

### Apply Filtering on Projects Table

In [89]:
filtered_hacks_id = filtered_hacks["id"].unique()
filtered_hacks_id

array([17851, 16823, 16348, ...,  5164,  5310,  4966])

In [90]:
filtered_projects = projects[
    projects['Hackathon ID'].isin(filtered_hacks_id)
]

In [91]:
filtered_projects.shape[0]

285678

### Get Projects Count for each hackathon

In [92]:
projects_per_hack = (
    filtered_projects.groupby('Hackathon ID')['Project Title'].count().reset_index(name = "Projects Count")
)

#### Add no. teams to its own hackathon (on hackathons table)

In [93]:
filtered_hacks = filtered_hacks.merge(
    projects_per_hack,
    left_on = 'id',
    right_on = "Hackathon ID",
    how = 'left',
)
filtered_hacks.head()

,id,Hackathon Slug,Title,Status,URL,Submission Period,Themes,Prize Amount,Registrations Count,Organization,Winners Announced,Projects Gallery,Hackathon ID,Projects Count
0,17851,bpt-hackathon,University of Bridgeport Hackathon,ended,https://bpt-hackathon.devpost.com/,"Apr 14 - 16, 2023","['E-commerce/Retail', 'Enterprise', 'Web']",2700,23,University of Bridgeport,True,https://bpt-hackathon.devpost.com/project-gallery,17851.0,4.0
1,16823,orange-inter-odc-makeathon,Orange Inter-ODC Makeathon 2022,ended,https://orange-inter-odc-makeathon.devpost.com/,"Dec 03 - 04, 2022","['IoT', 'Enterprise', 'Web']",6000,23,Orange Digital Center,True,https://orange-inter-odc-makeathon.devpost.com...,16823.0,12.0
2,16348,code-kevudah-hackathon,Code Kevudah Hackathon,ended,https://code-kevudah-hackathon.devpost.com/,"Nov 20, 2022","['Beginner Friendly', 'Open Ended']",4,23,Code Kevudah,True,https://code-kevudah-hackathon.devpost.com/pro...,16348.0,9.0
3,16685,taws,Datathon TAWS,ended,https://taws.devpost.com/,"Nov 11 - 12, 2022","['Beginner Friendly', 'Machine Learning/AI', '...",180,23,TAWS,True,https://taws.devpost.com/project-gallery,16685.0,6.0
4,16604,mccs-fall-2022,Marist College Computer Society Fall 2022,ended,https://mccs-fall-2022.devpost.com/,"Oct 22, 2022","['Beginner Friendly', 'Social Good']",0,23,IBM,True,https://mccs-fall-2022.devpost.com/project-gal...,16604.0,8.0

In [94]:
filtered_hacks = filtered_hacks.drop(columns='Hackathon ID')
filtered_hacks.head()

,id,Hackathon Slug,Title,Status,URL,Submission Period,Themes,Prize Amount,Registrations Count,Organization,Winners Announced,Projects Gallery,Projects Count
0,17851,bpt-hackathon,University of Bridgeport Hackathon,ended,https://bpt-hackathon.devpost.com/,"Apr 14 - 16, 2023","['E-commerce/Retail', 'Enterprise', 'Web']",2700,23,University of Bridgeport,True,https://bpt-hackathon.devpost.com/project-gallery,4.0
1,16823,orange-inter-odc-makeathon,Orange Inter-ODC Makeathon 2022,ended,https://orange-inter-odc-makeathon.devpost.com/,"Dec 03 - 04, 2022","['IoT', 'Enterprise', 'Web']",6000,23,Orange Digital Center,True,https://orange-inter-odc-makeathon.devpost.com...,12.0
2,16348,code-kevudah-hackathon,Code Kevudah Hackathon,ended,https://code-kevudah-hackathon.devpost.com/,"Nov 20, 2022","['Beginner Friendly', 'Open Ended']",4,23,Code Kevudah,True,https://code-kevudah-hackathon.devpost.com/pro...,9.0
3,16685,taws,Datathon TAWS,ended,https://taws.devpost.com/,"Nov 11 - 12, 2022","['Beginner Friendly', 'Machine Learning/AI', '...",180,23,TAWS,True,https://taws.devpost.com/project-gallery,6.0
4,16604,mccs-fall-2022,Marist College Computer Society Fall 2022,ended,https://mccs-fall-2022.devpost.com/,"Oct 22, 2022","['Beginner Friendly', 'Social Good']",0,23,IBM,True,https://mccs-fall-2022.devpost.com/project-gal...,8.0

In [95]:
filtered_hacks['Projects Count'] = filtered_hacks['Projects Count'].fillna(0).astype(int)
filtered_hacks.head()

,id,Hackathon Slug,Title,Status,URL,Submission Period,Themes,Prize Amount,Registrations Count,Organization,Winners Announced,Projects Gallery,Projects Count
0,17851,bpt-hackathon,University of Bridgeport Hackathon,ended,https://bpt-hackathon.devpost.com/,"Apr 14 - 16, 2023","['E-commerce/Retail', 'Enterprise', 'Web']",2700,23,University of Bridgeport,True,https://bpt-hackathon.devpost.com/project-gallery,4
1,16823,orange-inter-odc-makeathon,Orange Inter-ODC Makeathon 2022,ended,https://orange-inter-odc-makeathon.devpost.com/,"Dec 03 - 04, 2022","['IoT', 'Enterprise', 'Web']",6000,23,Orange Digital Center,True,https://orange-inter-odc-makeathon.devpost.com...,12
2,16348,code-kevudah-hackathon,Code Kevudah Hackathon,ended,https://code-kevudah-hackathon.devpost.com/,"Nov 20, 2022","['Beginner Friendly', 'Open Ended']",4,23,Code Kevudah,True,https://code-kevudah-hackathon.devpost.com/pro...,9
3,16685,taws,Datathon TAWS,ended,https://taws.devpost.com/,"Nov 11 - 12, 2022","['Beginner Friendly', 'Machine Learning/AI', '...",180,23,TAWS,True,https://taws.devpost.com/project-gallery,6
4,16604,mccs-fall-2022,Marist College Computer Society Fall 2022,ended,https://mccs-fall-2022.devpost.com/,"Oct 22, 2022","['Beginner Friendly', 'Social Good']",0,23,IBM,True,https://mccs-fall-2022.devpost.com/project-gal...,8

### Filter by projects count (Projects count > 5)

In [96]:
filtered_hacks = filtered_hacks[
    filtered_hacks["Projects Count"] > 5
]

### Filter by Year (2023-2025)

In [ ]:
# old_filtered_hacks=filtered_hacks[filtered_hacks['Submission Period'].str.contains('20[2][3-5]', na=False)]

In [ ]:
# old_filtered_hacks.shape[0]

2139

In [ ]:
# old_filtered_hacks_id = old_filtered_hacks["id"].unique()

In [ ]:
# old_filtered_projects = projects[
#     projects['Hackathon ID'].isin(old_filtered_hacks_id)
# ]

In [ ]:
# old_filtered_projects.shape[0]

106594

In [ ]:
# old_filtered_projects.head()

,Hackathon ID,Hackathon Slug,Project Title,Project Description,Project Link,Participants Count,Likes,Comments
117,22720,uaec,Wear-ify,Wear-ify records audio and transcribes it for ...,https://devpost.com/software/wear-ify,1,1,0
118,22720,uaec,BloodGuard,Empowering Cardiovascular patients one at a time,https://devpost.com/software/bloodguard,1,0,0
119,22720,uaec,Sightway,Directions and Obstacle detection for Visually...,https://devpost.com/software/sightway,1,0,0
120,22720,uaec,CalmAlert,CalmAlert protects mental health by detecting ...,https://devpost.com/software/calmalert,3,2,0
121,22720,uaec,StaySharp,Our program uses real-time heart rate data fro...,https://devpost.com/software/staysharp-3815uv,4,0,0

In [97]:
filtered_hacks=filtered_hacks[filtered_hacks['Submission Period'].str.contains('20[2][0-5]', na=False)]

In [98]:
filtered_hacks.shape[0]

4309

In [99]:
filtered_hacks_id = filtered_hacks["id"].unique()

In [100]:
filtered_projects = projects[
    projects['Hackathon ID'].isin(filtered_hacks_id)
]

### Filter projects by participants count

In [101]:
filtered_projects = filtered_projects[filtered_projects['Participants Count'].between(3,8)]

In [102]:
filtered_projects.shape[0]

85415

In [103]:
filtered_projects.head()

,Hackathon ID,Hackathon Slug,Project Title,Project Description,Project Link,Participants Count,Likes,Comments
5,16823,orange-inter-odc-makeathon,Owl4 -INSAT Team1,This solution is capable of automating the ind...,https://devpost.com/software/owl4,4,0,0
16,16348,code-kevudah-hackathon,Here We Go,"Here we go! Using our tool, you can determine ...",https://devpost.com/software/here-we-go-l0z7rv,5,0,0
19,16348,code-kevudah-hackathon,My Frum Calendar,Enables Orthodox Jewish women to balance the c...,https://devpost.com/software/my-frum-calendar,3,2,0
22,16348,code-kevudah-hackathon,מתכוני חיים - Recipes for Life,The Jewish Woman will cook at least 104 Shabba...,https://devpost.com/software/mother-s-helper,4,0,0
25,16685,taws,G5 -Data Warriors,Proyecto posi,https://devpost.com/software/g5-data-warriors,3,0,0

In [104]:
total_participants = filtered_projects['Participants Count'].sum()
print(f"Total participants in all projects: {total_participants}")

Total participants in all projects: 321996

In [ ]:
# filtered_projects = filtered_projects[filtered_projects['Participants Count'].between(3, 8)]

In [105]:
filtered_projects.shape[0]

85415

In [106]:
total_participants = filtered_projects['Participants Count'].sum()
print(f"Total participants in all projects: {total_participants}")

Total participants in all projects: 321996

In [107]:
filtered_projects.to_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/2020-2025_Projects.csv', index=False)

In [108]:
filtered_hacks.to_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/2020-2025_Hackathons.csv', index=False)

In [ ]:
# old_filtered_projects.to_csv('/content/drive/MyDrive/Datasets/old_projects.csv', index=False)

## Teams and Team Members Data Cleaning

In [50]:
teams = pd.read_csv('/content/drive/MyDrive/Datasets/2023/2023-2025_Teams.csv')
team_members = pd.read_csv('/content/drive/MyDrive/Datasets/2023/2023-2025_Team_Members.csv')

### Teams Cleaning

In [51]:
teams.head()

,Hackathon ID,Project Slug,Members Count,Is Winner,Winners Description,Project Tags,Project Description
0,21150,confluent-9vjykl,4,False,NaN,"['css', 'gemini', 'google-cloud', 'html', 'nod...",💥 - How it started With one of our close frien...
1,21150,journeyai,4,False,NaN,"['fetchai', 'figma', 'firebase', 'gemini', 'gi...",Inspiration Have you ever returned home from a...
2,21150,lamaps,4,False,NaN,"['daisyui', 'excalidraw', 'fastapi', 'networkx...",Inspiration Millions of people go on walks or ...
3,21150,trippy-25j9st,4,False,NaN,"['api', 'atlas', 'fast', 'fetchai', 'mongodb',...","Inspiration We think that everyone, regardless..."
4,21150,medscribe-vp3qzi,4,False,NaN,"['fastapi', 'next.js', 'openai', 'react']",Inspiration We have all experienced the long w...

In [52]:
teams.shape[0]

44107

In [53]:
teams.duplicated().sum()

np.int64(0)

### Check duplicates according to Project Slug

In [54]:
len(teams["Project Slug"].unique())

43240

In [55]:
filtered_teams = teams.drop_duplicates(subset="Project Slug")

In [56]:
filtered_teams.shape[0]

43240

In [ ]:
# filtered_teams = filtered_teams[filtered_teams['Is Winner']==False]

In [ ]:
# filtered_teams.shape[0]

28494

### Team Members Cleaning

In [57]:
team_members.head()

,Project Slug,Member Username,Member URL,Member Description
0,confluent-9vjykl,marcuskoh,https://devpost.com/marcuskoh,NaN
1,confluent-9vjykl,nickc1810,https://devpost.com/nickc1810,NaN
2,confluent-9vjykl,stevensegawa,https://devpost.com/stevensegawa,NaN
3,confluent-9vjykl,ethantu10,https://devpost.com/ethantu10,NaN
4,journeyai,justinnguyen80,https://devpost.com/justinnguyen80,NaN

In [58]:
team_members.shape[0]

164893

### Drop duplicates

In [59]:
team_members.duplicated().sum()

np.int64(3296)

In [60]:
filtered_team_members = team_members.drop_duplicates()

In [61]:
filtered_team_members.shape[0]

161597

In [62]:
len(filtered_team_members["Member Username"].unique())

122725

### Filtering by Private Users

In [63]:
len(filtered_team_members[
    filtered_team_members["Member Username"] == "private user"
])

1441

In [64]:
private_projects = filtered_team_members.loc[
    filtered_team_members["Member Username"] == "private user",
    "Project Slug"
].unique()

In [65]:
filtered_team_members = filtered_team_members[
    ~filtered_team_members["Project Slug"].isin(private_projects)
]

In [66]:
filtered_teams = filtered_teams[
    ~filtered_teams["Project Slug"].isin(private_projects)
]

In [67]:
# no. all teams (projects)
filtered_teams.shape[0]

41819

In [68]:
filtered_team_members.head()

,Project Slug,Member Username,Member URL,Member Description
0,confluent-9vjykl,marcuskoh,https://devpost.com/marcuskoh,NaN
1,confluent-9vjykl,nickc1810,https://devpost.com/nickc1810,NaN
2,confluent-9vjykl,stevensegawa,https://devpost.com/stevensegawa,NaN
3,confluent-9vjykl,ethantu10,https://devpost.com/ethantu10,NaN
4,journeyai,justinnguyen80,https://devpost.com/justinnguyen80,NaN

In [69]:
filtered_teams_slug = filtered_teams["Project Slug"].unique()

In [70]:
filtered_team_members = filtered_team_members[
    filtered_team_members['Project Slug'].isin(filtered_teams_slug)
]

In [71]:
filtered_team_members.shape[0]

156370

In [72]:
len(filtered_team_members['Member Username'].unique())

120320

In [ ]:
filtered_team_members.duplicated(subset='Member Username').sum()

np.int64(16893)

In [ ]:
unique_users_2020 = filtered_team_members.drop_duplicates(subset='Member Username')

In [ ]:
unique_users_2020.shape[0]

83143

In [ ]:
unique_users_2020.duplicated(subset='Member Username').sum()

np.int64(0)

In [ ]:
unique_users_2020.head()

,Project Slug,Member Username,Member URL,Member Description
3,ethical-sharks,bandiss06,https://devpost.com/bandiss06,NaN
4,ethical-sharks,sshiv5768,https://devpost.com/sshiv5768,NaN
5,ethical-sharks,bhattejas06,https://devpost.com/bhattejas06,NaN
9,shark-s-cafe,UmairJibran,https://devpost.com/UmairJibran,"I worked on fronted, and data management along..."
10,shark-s-cafe,zvmzaretskyi,https://devpost.com/zvmzaretskyi,I was idea creator and designer. Also worked o...

In [ ]:
new_members = pd.read_csv('/content/drive/MyDrive/Datasets/unique_members.csv')
win_members = pd.read_csv('/content/drive/MyDrive/Datasets/2020_unique_members.csv')

In [ ]:
new_members.shape[0]

120320

In [ ]:
win_members.shape[0]

31856

In [ ]:
scraping1 = new_members["Member Username"].unique()
scraping2 = win_members["Member Username"].unique()
all_scraping = np.concatenate([scraping1, scraping2])

In [ ]:
scraping1.shape[0]

120320

In [ ]:
scraping2.shape[0]

31856

In [ ]:
all_scraping.shape[0]

152176

In [ ]:
old_unique_users = unique_users_2020[
    ~unique_users_2020['Member Username'].isin(all_scraping)
]

In [ ]:
old_unique_users.shape[0]

68783

In [74]:
# old_unique_users.to_csv('/content/drive/MyDrive/Datasets/2020FinalDataset/non_winner_unique_members.csv', index=False)
filtered_teams.to_csv('/content/drive/MyDrive/Datasets/2023/2023-2025_filtered_Teams.csv', index=False)
filtered_team_members.to_csv('/content/drive/MyDrive/Datasets/2023/2023-2025_filtered_Team_Members.csv', index=False)

In [ ]:
print(old_unique_users.shape[0])
print(filtered_teams.shape[0])
print(filtered_team_members.shape[0])

68783
26464
100036

In [ ]:
unique_users_2020.head(185)

,Project Slug,Member Username,Member URL,Member Description
3,ethical-sharks,bandiss06,https://devpost.com/bandiss06,NaN
4,ethical-sharks,sshiv5768,https://devpost.com/sshiv5768,NaN
5,ethical-sharks,bhattejas06,https://devpost.com/bhattejas06,NaN
9,shark-s-cafe,UmairJibran,https://devpost.com/UmairJibran,"I worked on fronted, and data management along..."
10,shark-s-cafe,zvmzaretskyi,https://devpost.com/zvmzaretskyi,I was idea creator and designer. Also worked o...
...,...,...,...,...
318,grocery,mshi9696,https://devpost.com/mshi9696,NaN
319,grocery,YasinEhsan,https://devpost.com/YasinEhsan,NaN
320,hermes-cn1k7v,andychen5671,https://devpost.com/andychen5671,Building the framework of the website. Help co...
321,hermes-cn1k7v,Plezo,https://devpost.com/Plezo,NaN
322,hermes-cn1k7v,jackychan9711,https://devpost.com/jackychan9711,NaN

In [ ]:
filtered_projects.head()

,Hackathon ID,Hackathon Slug,Project Title,Project Description,Project Link,Participants Count,Likes,Comments
120,22720,uaec,CalmAlert,CalmAlert protects mental health by detecting ...,https://devpost.com/software/calmalert,3,2,0
121,22720,uaec,StaySharp,Our program uses real-time heart rate data fro...,https://devpost.com/software/staysharp-3815uv,4,0,0
122,22720,uaec,GoalGetters,Kids nowadays are all addicted to their iPads ...,https://devpost.com/software/goalgetters,3,0,0
123,22720,uaec,DriveSafe,"Maintaining Driving Alertness, One Brainwave a...",https://devpost.com/software/drivesafe-53nbyz,3,0,0
124,21461,green-farm-hacks,Club Central,The Ultimate Destination for All Things Studen...,https://devpost.com/software/club-central,4,20,6

In [ ]:
filtered_projects[filtered_projects["Project Link"] == "https://devpost.com/software/juncture"]

,Hackathon ID,Hackathon Slug,Project Title,Project Description,Project Link,Participants Count,Likes,Comments
73728,21150,la-hacks-2024,Juncture,Juncture simplifies the college club hunt thro...,https://devpost.com/software/juncture,4,0,0

In [ ]:
teams[teams["Project Slug"]== "juncture"]

Empty DataFrame
Columns: [Hackathon ID, Project Slug, Members Count, Is Winner, Winners Description, Project Tags, Project Description]
Index: []

In [ ]:
team_members[team_members["Project Slug"]== "juncture"]

Empty DataFrame
Columns: [Project Slug, Member Username, Member URL, Member Description]
Index: []

In [ ]:
filtered_projects.head()

,Hackathon ID,Hackathon Slug,Project Title,Project Description,Project Link,Participants Count,Likes,Comments
120,22720,uaec,CalmAlert,CalmAlert protects mental health by detecting ...,https://devpost.com/software/calmalert,3,2,0
121,22720,uaec,StaySharp,Our program uses real-time heart rate data fro...,https://devpost.com/software/staysharp-3815uv,4,0,0
122,22720,uaec,GoalGetters,Kids nowadays are all addicted to their iPads ...,https://devpost.com/software/goalgetters,3,0,0
123,22720,uaec,DriveSafe,"Maintaining Driving Alertness, One Brainwave a...",https://devpost.com/software/drivesafe-53nbyz,3,0,0
124,21461,green-farm-hacks,Club Central,The Ultimate Destination for All Things Studen...,https://devpost.com/software/club-central,4,20,6

In [ ]:
filtered_projects.shape[0]

44107

In [ ]:
filtered_teams.head()

,Hackathon ID,Project Slug,Members Count,Is Winner,Winners Description,Project Tags,Project Description
1,11288,ethical-sharks,3,False,NaN,"['bootstrap', 'css', 'django', 'html', 'keras'...",Inspiration We were inspired by the issue of i...
3,11288,shark-s-cafe,3,False,NaN,"['cockroachdb', 'dart', 'flutter', 'python']",Inspiration Help people and ecology What it do...
5,11288,selfloving-us-bot,3,False,NaN,"['bootstrap', 'bot', 'css', 'echoar', 'github'...",Inspiration Mental disorders affect one in fou...
6,11288,sharkoslac,3,False,NaN,"['bootstrap', 'css', 'ejs', 'express.js', 'htm...",INSPIRATION: We came to know about Shark Hacks...
7,11288,shark-attack,4,False,NaN,"['pygame', 'python']",Inspiration We wanted to create a simple 1 vs ...

In [ ]:
len(filtered_teams[filtered_teams["Is Winner"]==True]) # 20%

0

In [ ]:
len(filtered_teams[filtered_teams["Is Winner"]==False])

26464

In [ ]:
filtered_team_members.head(10)

,Project Slug,Member Username,Member URL,Member Description
3,ethical-sharks,bandiss06,https://devpost.com/bandiss06,NaN
4,ethical-sharks,sshiv5768,https://devpost.com/sshiv5768,NaN
5,ethical-sharks,bhattejas06,https://devpost.com/bhattejas06,NaN
9,shark-s-cafe,UmairJibran,https://devpost.com/UmairJibran,"I worked on fronted, and data management along..."
10,shark-s-cafe,zvmzaretskyi,https://devpost.com/zvmzaretskyi,I was idea creator and designer. Also worked o...
11,shark-s-cafe,jemsbhai,https://devpost.com/jemsbhai,NaN
16,selfloving-us-bot,Dibyansika,https://devpost.com/Dibyansika,NaN
17,selfloving-us-bot,sushreesatarupa-ss,https://devpost.com/sushreesatarupa-ss,NaN
18,selfloving-us-bot,sayansree-paria,https://devpost.com/sayansree-paria,NaN
19,sharkoslac,adi-dutta-2000,https://devpost.com/adi-dutta-2000,NaN

In [ ]:
filtered_team_members["Member Description"].isna().sum()

np.int64(68691)

In [ ]:
all_members = pd.read_csv('/content/drive/MyDrive/Datasets/all_members.csv')

In [ ]:
all_members.shape[0]

130308

In [ ]:
all_members.duplicated().sum()

np.int64(10320)

In [ ]:
filtered_all_members= all_members.drop_duplicates()

In [ ]:
filtered_all_members.duplicated().sum()

np.int64(0)

In [ ]:
filtered_all_members.head()

,Username,Name,Bio,Location,Website,GitHub,Hard Skills,Soft Skills,Projects Count,Hackathons Count,Achievements Count,Followers Count,Following Count,Like Count,Winnings Count
0,arjunsb26,arjunsb26 Bhat,NaN,"Fairfax, VA, US",https://github.com/arjunsb26,https://github.com/arjunsb26,"['java', 'python', 'flask', 'css', 'ml']","['AR/VR', 'Beginner Friendly', 'Blockchain', '...",3,3,6,1,1,0,1
1,akshithambekar,Akshith Ambekar,NaN,"Aldie, VA, US",NaN,NaN,,"['Beginner Friendly', 'Cybersecurity', 'Lifeha...",2,4,5,1,0,1,0
2,okovvali5,Omkar Kovvali,NaN,"Virginia, United States",NaN,NaN,['java'],['Health'],4,4,8,2,5,2,1
3,raghav-sriram5,Raghav S,NaN,"Herndon, Virginia, United States",NaN,NaN,"['python', 'java', 'javascript', 'c', 'c++']","['AR/VR', 'Blockchain', 'Cybersecurity', 'Data...",1,1,4,0,0,0,0
4,ppanicke,Pranav Panicker,NaN,"Virginia, United States",NaN,NaN,"['python', 'c', 'c++', 'ocaml', 'java']","['DevOps', 'Fintech', 'Machine Learning/AI']",1,1,4,0,0,0,0

In [ ]:
filtered_all_members.shape[0]

119988

In [ ]:
# filtered_all_members.to_csv('/content/drive/MyDrive/Datasets/filtered_all_members.csv', index=False)