In [3]:
import numpy as np
import pandas as pd
import ast
from google.colab import drive

In [4]:
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
members = pd.read_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/members_clean.csv')

In [6]:
members.shape

(179103, 12)

In [7]:
members.duplicated(subset='username').sum()

np.int64(0)

## Convert String Columns To Lists

In [8]:
def to_list(col):
    if isinstance(col, list):
        return col
    if isinstance(col, str):
        try:
            return ast.literal_eval(col)
        except:
            return []
    return []

In [9]:
members['hard_skills']=members['hard_skills'].apply(to_list)
# members['hackathons_interests']=members['hackathons_interests'].apply(to_list)
# members['Descriptions']=members['Descriptions'].apply(to_list)

## Map Hard Skills to (Hard Skills and Soft Skills)

### Hard Skills Column -> Hard Skills

In [10]:
members.head(3)

,username,bio,hard_skills,hackathons_interests,project_count,hackathons_count,achievements_count,followers_count,following_count,likes_count,winnings_count,Descriptions
0,dembiczakmatt,NaN,[],[],2,2,9,0,0,1,2,NaN
1,kkysharma2114,NaN,"[design, ui, ux, matlab, python, html]","['Beginner Friendly', 'Communication', 'Design...",3,7,6,6,0,3,0,NaN
2,pradeepkprakasam,Blockchain Developer,"[javascript, solidity, react, react-native, ma...","['Blockchain', 'Education', 'Fintech', 'IoT', ...",1,6,6,4,2,0,1,"[""I learned a lot about Self Sovereign Identit..."

In [11]:
members['hard_skills'].apply(type).value_counts()

hard_skills
<class 'list'>    179103
Name: count, dtype: int64

In [12]:
skills_count = members.explode('hard_skills')['hard_skills'].str.strip().str.lower().value_counts()

In [13]:
skills_count.shape

(15880,)

In [14]:
skills_count.head(100)

hard_skills
python        83292
java          52909
javascript    42906
c++           30119
react         21915
              ...
springboot      615
mern            606
ruby            596
ios             587
iot             585
Name: count, Length: 100, dtype: int64

In [15]:
skills_count=skills_count[skills_count>2]

In [16]:
skills_count.shape

(3949,)

In [17]:
skills_count_df = skills_count.reset_index()
skills_count_df.columns = ['skill', 'count']

In [18]:
skills_count_df.to_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/unique_skills.csv', index=False)

#### Mapping Soft Skills

In [19]:
SOFT_SKILL_MAP = {
    "adaptability": "adaptability",
    "adaptable": "adaptability",
    "adaptation": "adaptability",
    "adaptive": "adaptability",
    "adaptiveplanning": "adaptability",

    "creative": "creativity",
    "creative-thinking": "creativity",
    "creativity": "creativity",
    "creativethinking": "creativity",
    "ideation": "creativity",
    "innovation": "creativity",
    "innovative": "creativity",

    "beginner": "beginner",
    "beginner friendly": "beginner",

    "communication": "communication",
    "communications": "communication",
    "comunication": "communication",
    "communcation": "communication",
    "communicative": "communication",
    "comunicacion": "communication",
    "empathy": "communication",
    "friendly": "communication",
    "presentation": "communication",
    "presentation-skills": "communication",
    "presentations": "communication",
    "presenting": "communication",
    "public-speaking": "communication",
    "publicspeaking": "communication",
    "relationships": "communication",
    "social": "communication",
    "social good": "communication",
    "speaking": "communication",

    "collaboration": "collaborative",
    "accessibility": "accessibility",
    "sustainability":"sustainability",

    "community": "teamwork",
    "community-management": "teamwork",

    "team": "teamwork",
    "team-building": "teamwork",
    "team-coordination": "teamwork",
    "team-management": "teamwork",
    "team-player": "teamwork",
    "team-work": "teamwork",
    "teamplayer": "teamwork",
    "teams": "teamwork",
    "teamwork": "teamwork",
    "teamwork-live": "teamwork",
    "teamworking": "teamwork",

    "decision-making": "leadership",
    "lead": "leadership",
    "leader": "leadership",
    "leadership": "leadership",
    "leading": "leadership",
    "team-leader": "leadership",
    "team-leadership": "leadership",
    "teamleader": "leadership",

    "critical-thinking": "problem solving",
    "criticalthinking": "problem solving",
    "brainstorming": "problem solving",
    "problem-solving": "problem solving",
    "problem-solver": "problem solving",
    "problemsolving": "problem solving",
    "thinking": "problem solving",
    # "critical": "problem solving",

    "time-management": "time management",
    "timemanagement": "time management",

    "hardworking": "hard working",
    "learning": "learning",
    "learn": "learning",
    "learner": "learning",
    "elearning": "learning",
    "study": "learning",

    "productivity": "productivity",

    "lifehacks": "lifehacks",
    "hackathon": "hackathons",
    "hackathons": "hackathons",
    "hack": "hackathons",
    "hacks": "hackathons",

    "planning": "planning",

    "smart": "smart",
    "intelligence": "intelligence",
    "motivation": "motivation",
    "social-media": "communication",
    "social-actions": "communication",
    "social-impact": "communication",
    "social-skills": "communication",

    "organization": "organization",
    "organizations": "organization",
    "organizing": "organization",
    "organizer": "organization",
    "organized": "organization",
    "organizational": "organization",
    "organising": "organization",

    # "competitive": "competitive",
    "reading": "reading",
    "writing": "writing",
    "writting": "writing",
    "write": "writing",
    "creative-writing": "writing",

    "listening":"listening",
    "fun": "fun",
    "efficiency": "efficiency",

    #####
    # management


    # "narrative": "communication",
    # "partnership": "teamwork",
    # "partnerships": "teamwork",
    # "peoplemanagement": "leadership",
    # "problem": "problem solving",
    # "project": "project management",
    # "project-management": "leadership",
    # "project-manager": "leadership",
    # "project-planning": "leadership",
    # "projectmanagement": "leadership",
    # "scrum": "project management",
    # "agile": "project management",
    # "storytelling": "communication",
    # "research": "research",
    # "researcher": "research",
    # "researchr": "research",
    # "risk-management": "leadership",
    # "riskmanagement": "leadership",
    # "change-management": "leadership",
    # "changemanagement": "leadership",
    # "management": "leadership",
    # "managment": "leadership",
    # "manager": "leadership",
    # "managing": "leadership",
}

In [20]:
def split_soft_from_hard(hard_skills):
    mapped_soft = []
    hard_remaining = []

    if not isinstance(hard_skills, list):
        return [], []

    for skill in hard_skills:
        s = str(skill).lower().strip()

        if s in SOFT_SKILL_MAP:
            mapped_soft.append(SOFT_SKILL_MAP[s])
        else:
            hard_remaining.append(skill)

    # remove duplicates (keep unique)
    mapped_soft = list(set(mapped_soft))
    hard_remaining = list(set(hard_remaining))

    return hard_remaining, mapped_soft

In [21]:
members[["hard_skills_clean", "mapped_soft_skills"]] = members["hard_skills"].apply(
    lambda x: pd.Series(split_soft_from_hard(x))
)

In [22]:
members.to_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/mapped_members.csv', index=False)

## Filter Members don't have any hard skills

In [23]:
members.shape

(179103, 14)

In [24]:
# members don't have any skills
members['hard_skills'].apply(lambda x: isinstance(x, list) and len(x) == 0).sum()

np.int64(25263)

In [25]:
# members don't have any hard skills
members['hard_skills_clean'].apply(lambda x: isinstance(x, list) and len(x) == 0).sum()

np.int64(25856)

In [26]:
# members don't have any soft skills
members['mapped_soft_skills'].apply(lambda x: isinstance(x, list) and len(x) == 0).sum()

np.int64(175787)

### Drop Members don't have any skills

In [27]:
without_empty_skills_members = members[members['hard_skills_clean'].apply(lambda x: isinstance(x, list) and len(x) > 0)]

In [28]:
without_empty_skills_members.shape

(153247, 14)

In [29]:
without_empty_skills_members['mapped_soft_skills'].apply(lambda x: isinstance(x, list) and len(x) > 0).sum()

np.int64(2723)

### Drop their records with their projects from **Team Members** table

In [30]:
team_members = pd.read_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/team_members_clean.csv')

In [31]:
team_members.shape

(239200, 3)

In [32]:
missing_rows = team_members[~team_members['member_username'].isin(without_empty_skills_members['username'])]

In [33]:
missing_projects = missing_rows['project_slug'].unique()

In [34]:
without_empty_skills_team_members = team_members[~team_members['project_slug'].isin(missing_projects)]

In [35]:
without_empty_skills_team_members.shape

(145314, 3)

### Drop their projects from **Teams** table

In [36]:
teams = pd.read_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/teams_clean.csv')

In [37]:
teams.shape

(63527, 9)

In [38]:
without_empty_skills_teams = teams[~teams['project_slug'].isin(missing_projects)]

In [39]:
without_empty_skills_teams.shape

(39269, 9)

### Drop their projects from **Projects** table

In [40]:
projects = pd.read_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/projects_clean.csv')

In [41]:
without_empty_skills_projects = projects[~projects['project_slug'].isin(missing_projects)]

In [42]:
without_empty_skills_projects.shape

(39269, 7)

### Drop hackathos have missing projects from **Hackathons** table

In [43]:
hackathons = pd.read_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/hackathons_clean.csv')

In [44]:
hackathons.shape

(3396, 6)

In [45]:
without_empty_skills_hackathons = hackathons[hackathons['hackathon_slug'].isin(without_empty_skills_projects['hackathon_slug'])]

In [46]:
without_empty_skills_hackathons.shape

(3257, 6)

### Drop remaining members from **Members** table

In [47]:
without_empty_skills_members.shape

(153247, 14)

In [48]:
without_empty_skills_members = without_empty_skills_members[without_empty_skills_members['username'].isin(without_empty_skills_team_members['member_username'])]

In [49]:
without_empty_skills_members.shape

(112454, 14)

## Check all Table

In [50]:
len(without_empty_skills_hackathons[~without_empty_skills_hackathons['hackathon_id'].isin(without_empty_skills_projects['hackathon_id'])])

0

In [51]:
len(without_empty_skills_projects[~without_empty_skills_projects['hackathon_id'].isin(without_empty_skills_hackathons['hackathon_id'])])

0

In [52]:
len(without_empty_skills_projects[~without_empty_skills_projects['project_slug'].isin(without_empty_skills_teams['project_slug'])])

0

In [53]:
len(without_empty_skills_teams[~without_empty_skills_teams['project_slug'].isin(without_empty_skills_projects['project_slug'])])

0

In [54]:
len(without_empty_skills_teams[~without_empty_skills_teams['project_slug'].isin(without_empty_skills_team_members['project_slug'])])

0

In [55]:
len(without_empty_skills_team_members[~without_empty_skills_team_members['project_slug'].isin(without_empty_skills_teams['project_slug'])])

0

In [56]:
len(without_empty_skills_team_members[~without_empty_skills_team_members['member_username'].isin(without_empty_skills_members['username'])])

0

In [57]:
len(without_empty_skills_members[~without_empty_skills_members['username'].isin(without_empty_skills_team_members['member_username'])])

0

## Save Cleanded Tables after dropping members don't have any hard skill

In [58]:
print(without_empty_skills_hackathons.shape)
print(without_empty_skills_projects.shape)
print(without_empty_skills_teams.shape)
print(without_empty_skills_team_members.shape)
print(without_empty_skills_members.shape)

(3257, 6)
(39269, 7)
(39269, 9)
(145314, 3)
(112454, 14)

In [59]:
len(without_empty_skills_teams[without_empty_skills_teams['is_winner'] == True]) # 26%

10239

In [60]:
len(without_empty_skills_teams[without_empty_skills_teams['is_winner'] == False]) # 74%

29030

In [61]:
# without_empty_skills_hackathons.to_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/filtered_hackathons_clean.csv', index=False)
# without_empty_skills_projects.to_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/filtered_projects_clean.csv', index=False)
# without_empty_skills_teams.to_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/filtered_teams_clean.csv', index=False)
# without_empty_skills_team_members.to_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/filtered_team_members_clean.csv', index=False)
# without_empty_skills_members.to_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/filtered_mapped_members.csv', index=False)

## Drop projects don't have short description

In [62]:
without_empty_skills_projects['short_description'].isna().sum()

np.int64(20)

In [63]:
without_empty_skills_projects = without_empty_skills_projects.dropna(subset=['short_description'])
without_empty_skills_teams = without_empty_skills_teams.dropna(subset=['short_description'])

In [64]:
without_empty_skills_teams['short_description'].isna().sum()

np.int64(0)

### Clear remaining

#### Clear hackathons table

In [65]:
without_empty_skills_hackathons.shape

(3257, 6)

In [66]:
without_empty_skills_hackathons=without_empty_skills_hackathons[without_empty_skills_hackathons['hackathon_id'].isin(without_empty_skills_projects['hackathon_id'])]

In [67]:
without_empty_skills_hackathons.shape

(3257, 6)

#### Clear team members table

In [68]:
without_empty_skills_team_members.shape

(145314, 3)

In [69]:
without_empty_skills_team_members=without_empty_skills_team_members[without_empty_skills_team_members['project_slug'].isin(without_empty_skills_teams['project_slug'])]

In [70]:
without_empty_skills_team_members.shape

(145238, 3)

#### Clear members table

In [71]:
without_empty_skills_members.shape

(112454, 14)

In [72]:
without_empty_skills_members=without_empty_skills_members[without_empty_skills_members['username'].isin(without_empty_skills_team_members['member_username'])]

In [73]:
without_empty_skills_members.shape

(112421, 14)

## Drop Projects with > 2 Cold-Start members

In [74]:
without_empty_skills_team_members.shape

(145238, 3)

In [75]:
member_counts = without_empty_skills_team_members['member_username'].value_counts()
member_counts

member_username
jemsbhai          73
ebtesam686        54
IdkwhatImD0ing    41
Altaga            38
samurangedd       38
                  ..
Phaysik            1
dehaantyler        1
eplg2n             1
sylfw6             1
ahbmbd             1
Name: count, Length: 112421, dtype: int64

In [76]:
cold_members = member_counts[member_counts == 1].index

print(f"Number of unique members: {len(cold_members)}")

Number of unique members: 92527

In [77]:
without_empty_skills_team_members.shape

(145238, 3)

In [78]:
team_members_with_cold_start = without_empty_skills_team_members[without_empty_skills_team_members['member_username'].isin(cold_members)]
team_members_with_cold_start.head(10)

,project_slug,member_username,member_description
2,babel-fish-z2vdh6,gwatson1,NaN
3,babel-fish-z2vdh6,npope3,NaN
6,adventure-addict,DavidHouse,I worked on the UI and on connecting the back-...
23,sizeup-xl4kqi,DavidNguyen8,NaN
24,sizeup-xl4kqi,SlaughterGang,NaN
25,sizeup-xl4kqi,CadenErtel,NaN
26,sizeup-xl4kqi,afasiku1,NaN
34,test-name-mn8dow,manchijain61,NaN
35,study-buddy-lhmc0k,kyaw-t,NaN
36,study-buddy-lhmc0k,klee20,NaN

In [79]:
project_counts = team_members_with_cold_start['project_slug'].value_counts()
print(f"Number of projects with cold start: {len(project_counts)}")

Number of projects with cold start: 33103

In [80]:
project_counts

project_slug
aidbind-g3k5f0                                 8
fluopoc                                        8
galena-databook                                8
healapp                                        8
epam-nextfuture                                8
                                              ..
trivery                                        1
actually-useful-weather-utility-actuallyuwu    1
hopehub                                        1
m-ba2lfb                                       1
disser-royalhackaway2022                       1
Name: count, Length: 33103, dtype: int64

In [81]:
projects_with_g2cold = project_counts[project_counts > 2].index
print(f"Number of projects with more than 2 cold start members: {len(projects_with_g2cold)}")

Number of projects with more than 2 cold start members: 20680

In [82]:
team_members_without_cold = without_empty_skills_team_members[~without_empty_skills_team_members['project_slug'].isin(projects_with_g2cold)]
team_members_without_cold.shape

(66553, 3)

In [83]:
print(without_empty_skills_members.shape)
members_without_cold = without_empty_skills_members[without_empty_skills_members['username'].isin(team_members_without_cold['member_username'])]
print(members_without_cold.shape)

(112421, 14)
(38462, 14)

In [84]:
print(without_empty_skills_teams.shape)
teams_without_cold = without_empty_skills_teams[without_empty_skills_teams['project_slug'].isin(team_members_without_cold['project_slug'])]
print(teams_without_cold.shape)

(39249, 9)
(18569, 9)

In [85]:
print(without_empty_skills_projects.shape)
projects_without_cold = without_empty_skills_projects[without_empty_skills_projects['project_slug'].isin(team_members_without_cold['project_slug'])]
print(projects_without_cold.shape)

(39249, 7)
(18569, 7)

In [86]:
print(without_empty_skills_hackathons.shape)
hackathons_without_cold = without_empty_skills_hackathons[without_empty_skills_hackathons['hackathon_id'].isin(projects_without_cold['hackathon_id'])]
print(hackathons_without_cold.shape)

(3257, 6)
(2742, 6)

In [87]:
print(f'Hackathons -> {hackathons_without_cold.shape}')
print(f'Projects -> {projects_without_cold.shape}')
print(f'Teams -> {teams_without_cold.shape}')
print(f'Team Members -> {team_members_without_cold.shape}')
print(f'Members -> {members_without_cold.shape}')

Hackathons -> (2742, 6)
Projects -> (18569, 7)
Teams -> (18569, 9)
Team Members -> (66553, 3)
Members -> (38462, 14)

## Convert slugs to ids

### Drop hackathon slug from All Tables

In [88]:
ids_hackathons = hackathons_without_cold.drop(columns='hackathon_slug')

In [89]:
ids_projects = projects_without_cold.drop(columns='hackathon_slug')

In [90]:
ids_teams = teams_without_cold.drop(columns='hackathon_slug')

### Generate Projects ids

In [91]:
ids_projects = ids_projects.sort_values('project_slug').reset_index(drop=True)
ids_projects['project_id'] = ids_projects.index

In [92]:
ids_projects = ids_projects.drop(columns='participants_count')

In [93]:
ids_projects = ids_projects[['project_id'] + [c for c in ids_projects.columns if c != 'project_id']]

In [94]:
ids_projects.columns

Index(['project_id', 'hackathon_id', 'short_description', 'likes', 'comments',
       'project_slug'],
      dtype='object')

#### Add Project id to Teams table

In [95]:
ids_teams = ids_teams.merge(
    ids_projects[['project_slug', 'project_id']],
    on='project_slug',
    how='left'
)

In [96]:
ids_teams = ids_teams[['project_id'] + [c for c in ids_teams.columns if c != 'project_id']]

In [97]:
ids_teams = ids_teams.sort_values(by="project_id", ascending=True)

#### Add Project id to Team Members table

In [98]:
ids_team_members = team_members_without_cold.merge(
    ids_projects[['project_slug', 'project_id']],
    on='project_slug',
    how='left'
)

In [99]:
ids_team_members = ids_team_members.sort_values(by="project_id", ascending=True)

In [100]:
ids_team_members.columns

Index(['project_slug', 'member_username', 'member_description', 'project_id'], dtype='object')

#### Drop project slug from all tables

In [101]:
ids_projects = ids_projects.drop(columns='project_slug')
ids_teams = ids_teams.drop(columns='project_slug')
ids_team_members = ids_team_members.drop(columns='project_slug')

### Generate Members ids

In [102]:
ids_members = members_without_cold.sort_values('username').reset_index(drop=True)
ids_members['member_id'] = ids_members.index

In [103]:
ids_members = ids_members[['member_id'] + [c for c in ids_members.columns if c != 'member_id']]

#### Add member id to team members table

In [104]:
ids_team_members = ids_team_members.merge(
    ids_members[['username', 'member_id']],
    left_on='member_username',
    right_on='username',
    how='left'
)

In [105]:
ids_team_members = ids_team_members[['project_id'] + ['member_id'] + ['member_description']]

### Drop username column

In [106]:
ids_members.columns

Index(['member_id', 'username', 'bio', 'hard_skills', 'hackathons_interests',
       'project_count', 'hackathons_count', 'achievements_count',
       'followers_count', 'following_count', 'likes_count', 'winnings_count',
       'Descriptions', 'hard_skills_clean', 'mapped_soft_skills'],
      dtype='object')

In [107]:
ids_members = ids_members.drop(columns='username')

In [108]:
ids_members.rename(
    columns={
        'project_count': 'projects_count'
    },
    inplace=True
)

In [109]:
ids_members.columns

Index(['member_id', 'bio', 'hard_skills', 'hackathons_interests',
       'projects_count', 'hackathons_count', 'achievements_count',
       'followers_count', 'following_count', 'likes_count', 'winnings_count',
       'Descriptions', 'hard_skills_clean', 'mapped_soft_skills'],
      dtype='object')

## Check all Table

In [110]:
len(ids_hackathons[~ids_hackathons['hackathon_id'].isin(ids_projects['hackathon_id'])])

0

In [111]:
len(ids_projects[~ids_projects['hackathon_id'].isin(ids_hackathons['hackathon_id'])])

0

In [112]:
len(ids_projects[~ids_projects['project_id'].isin(ids_teams['project_id'])])

0

In [113]:
len(ids_teams[~ids_teams['project_id'].isin(ids_projects['project_id'])])

0

In [114]:
len(ids_teams[~ids_teams['project_id'].isin(ids_team_members['project_id'])])

0

In [115]:
len(ids_team_members[~ids_team_members['project_id'].isin(ids_teams['project_id'])])

0

In [116]:
len(ids_team_members[~ids_team_members['member_id'].isin(ids_members['member_id'])])

0

In [117]:
len(ids_members[~ids_members['member_id'].isin(ids_team_members['member_id'])])

0

## Save Updated Tables

In [118]:
print(ids_hackathons.shape)
print(ids_projects.shape)
print(ids_teams.shape)
print(ids_team_members.shape)
print(ids_members.shape)

(2742, 5)
(18569, 5)
(18569, 8)
(66553, 3)
(38462, 14)

In [137]:
ids_hackathons.head(3)

,hackathon_id,themes,prize_amount,registrations_count,projects_count
6,14985,"['Beginner Friendly', 'COVID-19', 'Social Good']",216,23,6
8,13144,"['Beginner Friendly', 'Machine Learning/AI', '...",550,23,7
9,21461,"['Education', 'Productivity', 'Social Good']",0,22,6

In [128]:
test = ids_members.drop(columns=["hard_skills_clean", "mapped_soft_skills"])

In [130]:
# Rename 'hard_skills' to 'skills' in place
test.rename(columns={'hard_skills': 'skills'}, inplace=True)

In [132]:
# Define your desired column order
new_order = ['member_id', 'bio', 'skills', 'hackathons_interests', 'Descriptions']

# Reorder the DataFrame
test = test[new_order]

In [133]:
test.head(3)

,member_id,bio,skills,hackathons_interests,Descriptions
0,0,NaN,"[python, machine-learning, flask, django, fast...","['Machine Learning/AI', 'Productivity', 'Begin...",['I helped out with a mostly everything. I als...
1,1,High school student with a passion for applyin...,"[python, javascript, java]","['Beginner Friendly', 'Low/No Code', 'Machine ...",NaN
2,2,NaN,"[python, javascript]","['Cybersecurity', 'DevOps', 'Gaming', 'IoT', '...",['I used SAP BTP to implement and deploy the b...

In [127]:
ids_members.head(3)

,member_id,bio,hard_skills,hackathons_interests,projects_count,hackathons_count,achievements_count,followers_count,following_count,likes_count,winnings_count,Descriptions,hard_skills_clean,mapped_soft_skills
0,0,NaN,"[python, machine-learning, flask, django, fast...","['Machine Learning/AI', 'Productivity', 'Begin...",4,25,7,14,12,41,4,['I helped out with a mostly everything. I als...,"[django, python, react, machine-learning, fast...",[]
1,1,High school student with a passion for applyin...,"[python, javascript, java]","['Beginner Friendly', 'Low/No Code', 'Machine ...",1,3,5,2,2,1,0,NaN,"[python, javascript, java]",[]
2,2,NaN,"[python, javascript]","['Cybersecurity', 'DevOps', 'Gaming', 'IoT', '...",3,3,5,0,0,1,0,['I used SAP BTP to implement and deploy the b...,"[python, javascript]",[]

In [119]:
ids_hackathons.to_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/hackathons_without_cold.csv', index=False)
ids_projects.to_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/projects_without_cold.csv', index=False)
ids_teams.to_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/teams_without_cold.csv', index=False)
ids_team_members.to_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/team_members_without_cold.csv', index=False)
ids_members.to_csv('/content/drive/MyDrive/Datasets/2020-2025_Devpost_Dataset/Cleaned_Dataset/mapped_members_without_cold.csv', index=False)